config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :comments 

  root 'welcome#index'


  # Google Auth routing
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')
  get 'me', to: 'me#show', as: 'me'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :comment, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
    def self.find_or_create_from_auth_hash(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.first_name = auth.info.first_name
            user.last_name = auth.info.last_name
            user.email = auth.info.email
            user.picture = auth.info.image
            user.save!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user


    def authenticate
        if !user_signed_in?
            redirect_to :root
        end

    end


    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end


    def login_error
        @login_error ||= nil
    end


    def user_signed_in?
        # Ruby falsy values
        !!current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate
    
    def index
        @comments = Comment.all

        @comments = @comments.sort do |comment, other_comment|
            other_comment.updated_at <=> comment.updated_at
        end
    end
    
    
    def show
        @comment = Comment.find(params[:id])
    end
    
    
    def new
        @comment = Comment.new
    end

    
    def edit
        @comment = Comment.find(params[:id])
    end

    
    def create
        @comment = Comment.new(comment_params)    

        if @comment.save
            redirect_to @comment
        else
            render 'new'
        end
    end


    def update
        @comment = Comment.find(params[:id])

        if @comment.update(comment_params)
            redirect_to @comment
        else
            render 'edit'
        end
    end

    
    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy

        redirect_to comments_path
    end
    

    private
        def comment_params
            params.require(:comment).permit(:name, :comment)
        end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
    before_action :authenticate
    def show
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
  	@user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
	session[:user_id] = @user.id
	session[:email] = @user.email
	session[:picture] = @user.picture
  	redirect_to :comments
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to comments_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_with model: @comment , local: true do |form| %>

    <% if @comment.errors.any? %>
        <div id="error_explanation">
            <%= pluralize(@comment.errors.count, "error") %>
            prohibited this article from being saved:
        </div>
        <li>
            <%= @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </li>
    <% end %>

    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
    </p>

    <p>
        <%= form.label :comment %><br>
        <%= form.text_area :comment %>
    </p>

    <p>
        <%= form.label :picture %><br>
        <%= form.text_field :picture, value:current_user.attributes["picture"] %>

    </p>

    <p>
        <%= form.submit %>
    </p>
    
<% end %>

app/views/comments/_header.html.erb
<div class="align-self-right">

</div>


<nav class="navbar  navbar-dark bg-dark">
   <a class="navbar-brand" href="<%= comments_path %>">Home</a>

    <li class="nav-item btn btn-light">
      <a class="nav-link" href="http://localhost:3000/logout" tabindex="-1">Log Out</a>
    </li>
</nav> <br>

app/views/comments/edit.html.erb
<%= render 'header' %>

<div class="container">
    <h1>Edit Comment</h1>

    <%= render 'form' %>

    <%= link_to 'Back', comments_path %>

</div>

app/views/comments/index.html.erb
<%= render 'header' %>

<div class="container">
    <h1>Community Thoughts</h1>

    <a class="btn btn-primary" href="<%= new_comment_path %>"> New Comment </a>
    <br><br><br>

    
    <% @comments.each do |comment| %>

        <div class="card bg-dark text-light" style="width: 25rem;">
            <img src="https://cdn.pixabay.com/photo/2019/02/26/11/49/small-4021848_960_720.jpg" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title"><%= comment.name %></h5>
                <p class="card-text"><%= comment.comment %></p>
                <%= link_to 'Edit comment', edit_comment_path(comment) %><br>
                <%= link_to 'Delete comment', comment_path(comment),
                    method: :delete,
                    data: { confirm: 'Are you sure?' }
                %>
            </div>
            <div class="card-body time-stamp">
                <p>Created: <%= comment.created_at %><br>
                Updated: <%= comment.updated_at %></p>
            </div>
        </div><br>
        
    <% end %>
</div>

app/views/comments/new.html.erb
<%= render 'header' %>

<div class="container">
    <h1>New comment!</h1>

    <%= render 'form' %>

    <%= link_to 'Back', comments_path %>
</div>

app/views/comments/show.html.erb
<%= render 'header' %>

<div class="container">
    <p>
        <strong>Name:</strong>
        <%= @comment.name %>
    </p>

    <p>
        <strong>Comment:</strong>
        <%= @comment.comment %>
    </p>


    <p>
        <strong>Img:</strong>
        <img src="<%= @comment.picture %>">
    </p>

    <%= link_to 'Edit', edit_comment_path %>
    <%= link_to 'Back', comments_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/me/show.html.erb
<% if current_user %>
    <% current_user.attributes.each do |key, val| %>
        <% if key == 'picture' %>
            <img src="<%= val %>">
        <% else %>
            <p>
                <%= key %>: <%= val %>
            </p>
            <% end %>
    <% end %>
<% end %>

app/views/welcome/index.html.erb
<div class="container">
    <h1>Community Thoughts</h1>

    <a class="btn btn-primary" href="/auth/google_oauth2" role="button">Sign in with Google</a>
</div>